tests: New unit tests for submoduling
titanscouting/red-alliance-analysis pull request #66
Opened 2020-12-10 02:02 UTC by zpan1

New tests for: Array, ClassificationMetric, CorrelationTest, KNN, NaiveBayes, RandomForest, SVM
Also some fixes

2020-12-10 02:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/titanscouting/red-alliance-analysis?pullRequest=66) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/titanscouting/red-alliance-analysis?pullRequest=66) before we can accept your contribution.<br/>**4** out of **5** committers have signed the CLA.<br/><br/>:white_check_mark: AGawde05<br/>:white_check_mark: devksingh4<br/>:white_check_mark: jzpan1<br/>:white_check_mark: ltcptgeneral<br/>:x: =<br/><hr/>**=** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/titanscouting/red-alliance-analysis?pullRequest=66) it.</sub>

2020-12-10 02:09 UTC, devksingh4 commented
@zpan1 and potentially @ltcptgeneral: why is github actions not running the unit tests?

2020-12-16 03:04 UTC, ltcptgeneral commented
Gonna wait to review until floating point issues are resolved

2020-12-30 01:38 UTC, ltcptgeneral requested changes

2020-12-30 01:38 UTC, ltcptgeneral commented on analysis-master/test_analysis.py
> +	#assert CorrelationTest.mgc()
fix floating point issues

2021-01-27 03:45 UTC, ltcptgeneral approved these changes
LGTM.

2021-01-27 03:46 UTC, merged

2021-01-27 03:51 UTC, ltcptgeneral commented
close #51